# Generated by Django 4.1.2 on 2022-11-04 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_title_lyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(verbose_name=datetime.datetime),
        ),
    ]
