# Generated by Django 4.1.2 on 2022-11-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_song_date_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='keyword',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
