# Generated by Django 4.1.2 on 2022-11-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_lyric_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='keyword',
        ),
    ]
